PePets/Controllers/BreedController.cs
using Microsoft.AspNetCore.Mvc;
using PePets.Models;
using PePets.Repositories;
using System;
using System.Threading.Tasks;

namespace PePets.Controllers
{
    /// <summary>
    /// Контроллер для управления породами животных.
    /// </summary>
    public class BreedController : Controller
    {
        private readonly IBreedRepository _breedRepository;
        private readonly ITypeRepository _typeRepository;

        public BreedController(IBreedRepository breedRepository, ITypeRepository typeRepository) 
        {
            _breedRepository = breedRepository;
            _typeRepository = typeRepository;
        }

        public IActionResult Index() 
        {
            return View();
        }

        /// <summary>
        /// Метод создает новую породу для определенного типа животного.
        /// </summary>
        /// <param name="typeId">Идентификатор типа животного, для которого создается новая порода.</param>
        /// <param name="breedName">Название новой породы.</param>
        /// <returns>
        /// При удачном создании редирект на страницу панели администрирования, при неудачном - возвращает
        /// частичное представление с ошибками создания породы.
        /// </returns>
        public async Task<IActionResult> Create(Guid typeId, string breedName)
        {
            if (!string.IsNullOrEmpty(breedName))
            {
                var type = await _typeRepository.GetByIdAsync(typeId);
                if (type != null)
                {
                    var breed = new BreedOfPet { Type = type, Breed = breedName };
                    await _breedRepository.CreateAsync(breed);

                    return RedirectToAction("Index", "Roles");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Такая порода уже есть в списке");
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Поле не может быть пустым");
            }

            return PartialView(breedName);
        }

        /// <summary>
        /// Метод удаляет определенную породу из списка.
        /// </summary>
        /// <param name="id">Идентификатор породы, которую нужно удалить.</param>
        /// <returns>Редирект на страницу панели администрирования.</returns>
        public async Task<IActionResult> Delete (Guid id)
        {
            var breed = await _breedRepository.GetByIdAsync(id);
            if (breed != null)
                await _breedRepository.DeleteAsync(breed);

            return RedirectToAction("Index", "Roles");
        }

        /// <summary>
        /// Метод загружает компонент списка пород для определенного типа животного.
        /// </summary>
        /// <param name="typeName">Название типа животного, для которого нужно загрузить список пород.</param>
        /// <returns>Компонент списка пород для определенного типа животного.</returns>
        [HttpGet]
        public IActionResult LoadBreedsViewComponent(string typeName)
        {
            return ViewComponent("BreedsList", typeName);
        }
    }
}

PePets/Controllers/TypeController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PePets.Models;
using PePets.Repositories;

namespace PePets.Controllers
{
    /// <summary>
    /// Контроллер для управления типами животных.
    /// </summary>
    public class TypeController : Controller
    {
        private readonly ITypeRepository _typeRepository;
        public TypeController(ITypeRepository typeRepository)
        {
            _typeRepository = typeRepository;
        }

        public IActionResult Index() => View();

        /// <summary>
        /// Метод создает новый тип животного с определенным названием.
        /// </summary>
        /// <param name="typeName">Название нового типа животного.</param>
        /// <returns>
        /// При удачном создании редирект на страницу панели администрирования, при неудачном - возвращает
        /// частичное представление с ошибками создания типа.
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> Create(string typeName)
        {
            if (!string.IsNullOrEmpty(typeName))
            {
                if (await _typeRepository.GetByNameAsync(typeName) == null)
                {
                    var type = new TypeOfPet { Type = typeName };
                    await _typeRepository.CreateAsync(type);

                    return RedirectToAction("Index", "Roles");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Такой вид уже есть в списке");
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Поле не может быть пустым");
            }

            return PartialView(typeName);
        }

        /// <summary>
        /// Метод удаляет определенный тип животного.
        /// </summary>
        /// <param name="id">Идентификатор типа животного, которое нужно удалить.</param>
        /// <returns>Редирект на панель администрирования.</returns>
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var type = await _typeRepository.GetByIdAsync(id);
            if(type != null)
                await _typeRepository.DeleteAsync(type);

            return RedirectToAction("Index", "Roles");
        }
    }
}

PePets/Views/Roles/Components/TypesList/TypesList.cshtml
@model IEnumerable<PePets.Models.TypeOfPet>

    <h2>Список видов животных</h2>
    <div class="p-1 overflow-auto shadow admin-panel">
        <!-- Список видов -->
        <div class="accordion" id="accordionTypes">
            <!-- Список пород одного типа -->
            @foreach (TypeOfPet type in Model)
            {
                <div class="card">

                    <!-- Заголовок вида -->
                    <div class="card-header" id=@("heading_" + type.Type)>
                        <div class="row align-items-center">
                            <div class="col col-9">
                                <button class="btn text-left w-100" type="button" data-toggle="collapse" data-target=@("#collapse_" + @type.Id) aria-expanded="true" aria-controls=@("collapse_" + @type.Id)>
                                    <h5><i class="fas fa-caret-down"></i> @type.Type</h5>
                                </button>
                            </div>
                            <div class="col col-3">
                                <form asp-controller="Type" asp-action="Delete" asp-route-id="@type.Id" method="post">
                                    <button class="btn btn-sm btn-danger w-100" type="submit">Удалить</button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- Список пород -->
                    <div id=@("collapse_" + @type.Id) class="collapse" aria-labelledby=@("heading_" + type.Type) data-parent="#accordionTypes">
                        <div class="card-body">
                            @await Component.InvokeAsync("BreedsList", type.Type)

                            <!-- Добавление новой породы -->
                            <div>
                                <div asp-validation-summary="All" class="text-danger"></div>

                                <form asp-controller="Breed" asp-action="Create" method="post" id="newBreed">
                                    <input type="hidden" name="typeId" value=@type.Id />
                                    <label for="breedName">Новая порода</label>
                                    <div class="row">
                                        <div class="col col-9 form-group">
                                            <input name="breedName" class="form-control" placeholder="Название новой породы" required />
                                        </div>

                                        <div class="col col-3">
                                            <button type="submit" class="btn btn-primary">Добавить</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

        <!-- Добавление нового вида -->
        <div>
            <div asp-validation-summary="All" class="text-danger"></div>

            <form asp-controller="Type" asp-action="Create" method="post">
                <label for="typeName">Новый вид</label>
                <div class="row">
                    <div class="col col-9 form-group">
                        <input name="typeName" class="form-control" placeholder="Название нового вида" required />
                    </div>

                    <div class="col col-3">
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </div>
            </form>
        </div>

    </div>