PePets/Controllers/PostsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PePets.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using PePets.Services;
using PePets.Repositories;

namespace PePets.Controllers
{
    /// <summary>
    /// Контроллер для управления объявлениями.
    /// </summary>
    public class PostsController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly IUserRepository _userRepository;
        private readonly IWebHostEnvironment _appEnvironment;
        private readonly int maxImagesCount;
        private readonly SearchService _searchService;

        public PostsController(IPostRepository postRepository, IUserRepository userRepository, IWebHostEnvironment appEnvironment, SearchService searchService)
        {
            _postRepository = postRepository;
            _userRepository = userRepository;
            _appEnvironment = appEnvironment;
            _searchService = searchService;
            maxImagesCount = 10;
        }

        /// <summary>
        /// Метод подгружает объявление для его подробного просмотра.
        /// </summary>
        /// <param name="id">Идентификатор объявления, которое необходимо просмотреть.</param>
        /// <returns>Представление определенного объявления.</returns>
        [HttpGet]
        public async Task<IActionResult> ReviewPost(Guid id)
        {
            Post post = await _postRepository.GetByIdAsync(id);
            await _postRepository.AddViewAsync(post);
            return View(post);
        }

        /// <summary>
        /// Метод подгружает страницу для создания объявления.
        /// </summary>
        /// <returns>Представление создания нового объявления.</returns>
        [HttpGet]
        [Authorize]
        public IActionResult CreatePost()
        {
            return View(new Post());
        }

        /// <summary>
        /// Метод создает новое объявление.
        /// </summary>
        /// <param name="post">Модель объявлния, которое нужно создать.</param>
        /// <param name="phoneNumberSwitch">Информация со свитча, нужно ли указывать телефон из профиля пользователя.</param>
        /// <param name="images">Коллекция фотографий, которые нужно добавить к объявлению.</param>
        /// <returns>
        /// При удачном создании объявления редирект на главную страницу, при неудачном - представление создания
        /// объявления с ошибками, возникшими при создании объявления.
        /// </returns>
        [HttpPost]
        [RequestSizeLimit(31457280)] // 30 Мб
        public async Task<IActionResult> CreatePost(Post post, string phoneNumberSwitch, IFormFileCollection images)
        {
            User currentUser = _userRepository.GetCurrentUser(User);

            // Если включена опция вставки номера в объявление из профиля пользователя.
            if (phoneNumberSwitch == "on")
                post.PhoneNumber = currentUser.PhoneNumber;

            // Корректно ли объявление.
            if (!CheckPost(post, phoneNumberSwitch, images.Count))
                return View(post);

            // Создаем запись в БД для получения идентификатора поста, чтобы сформировать названия фотографий.
            await _postRepository.CreateAsync(post);

            // Сохранение изображений в отдельную папку и добавление их путей в БД.
            post.Images = SaveImages(post.Id, images);

            //Добавление актуальной даты публикации.
            post.PublicationDate = DateTime.Now;

            // Кто создал объявление.
            await _userRepository.AddPostAsync(currentUser, post);

            // Обновляем запись объявления в БД.
            await _postRepository.UpdateAsync(post);

            // Индексирование данных.
            await _searchService.IndexPost(post);

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Метод подгружает страницу редактирования определенного объявления.
        /// </summary>
        /// <param name="id">Идентификатор объявления, которое нужно отредактировать.</param>
        /// <returns>Представление редактирования определенного объявления.</returns>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> EditPost(Guid id)
        {
            Post post = await _postRepository.GetByIdAsync(id);
            if (User.Identity.Name != post.User.UserName)
                return NotFound();

            return View("CreatePost", post);
        }

        /// <summary>
        /// Метод редактирования определенного объявление.
        /// </summary>
        /// <param name="post">Модель объявлния, которое нужно отредактировать.</param>
        /// <param name="phoneNumberSwitch">Информация со свитча, нужно ли указывать телефон из профиля пользователя.</param>
        /// <param name="images">Коллекция фотографий, которые нужно добавить к объявлению.</param>
        /// <returns>
        /// При удачном редактировании объявления редирект на главную страницу, при неудачном - представление
        /// редактирования объявления с ошибками, возникшими при редактировании.
        /// </returns>
        [HttpPost]
        [RequestSizeLimit(31457280)] // 30 Мб
        public async Task<IActionResult> EditPost(Post post, string phoneNumberSwitch, IFormFileCollection images)
        {
            User currentUser = _userRepository.GetCurrentUser(User);

            // Если включена опция вставки номера в объявление из профиля пользователя.
            if (phoneNumberSwitch == "on")
                post.PhoneNumber = currentUser.PhoneNumber;

            // Корректно ли объявление.
            if (!CheckPost(post, phoneNumberSwitch, images.Count))
                return View(post);

            // Сохранение изображений в отдельную папку и добавление их путей в БД.
            post.Images = SaveImages(post.Id, images);

            // Обноваление записи объявления в БД.
            await _postRepository.UpdateAsync(post);

            // Индексирование данных.
            await _searchService.IndexPost(post);

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Метод удаляет определенное объявление.
        /// </summary>
        /// <param name="id">Идентификатор объявления, которое нужно удалить.</param>
        /// <returns>Редирект на главную страницу.</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeletePost(Guid id)
        {
            Post postToDelete = await _postRepository.GetByIdAsync(id);

            // Удаление изображений с сервера.
            if(postToDelete.Images.Length > 0)
                DeleteAllImages(postToDelete.Images);

            // Удаление записи в БД.
            await _postRepository.DeleteAsync(postToDelete);

            // Удаление индекса
            await _searchService.DeleteIndexAsync(id.ToString());

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Метод добавляет или удаляет объявление в избранное.
        /// </summary>
        /// <param name="id">Идентификатор объявления.</param>
        /// <returns>Если объявление удалено из избранного - false, если добавлено - true.</returns>
        [HttpGet]
        public async Task<bool> Like(Guid id)
        {
            Post post = await _postRepository.GetByIdAsync(id);
            User currentUser = _userRepository.GetCurrentUser(User);

            // Если объявление уже добавленно в избранное,
            if (_userRepository.IsFavoritePost(User, id))
            {
                // то удаляем его,
                await _postRepository.UnlikeAsync(post);
                await _userRepository.DeleteFavoritePostAsync(currentUser, post);
                return false;
            }
            else
            {
                // иначе добавляем в избранное.
                await _postRepository.LikeAsync(post);
                await _userRepository.AddFavoritePostAsync(currentUser, post);
                return true;
            }  
        }

        private bool CheckPost(Post post, string phoneNumberSwitch, int imagesCount)
        {
            if (phoneNumberSwitch == "on")
            {
                if (string.IsNullOrEmpty(post.PhoneNumber))
                    ModelState.AddModelError(nameof(post.PhoneNumber),
                        "В вашем профиле не указан номер телефона, заполните поле самостоятельно");
            }

            if (string.IsNullOrEmpty(post.PhoneNumber) || post.PhoneNumber.Length < 12)
                ModelState.AddModelError(nameof(post.PhoneNumber), "Укажите номер телефона");

            if (imagesCount > maxImagesCount)
                ModelState.AddModelError(nameof(post.Images), "Нельзя загружать больше 10 изображений");

            return ModelState.IsValid;
        }

        private string[] SaveImages(Guid postId, IFormFileCollection images)
        {
            Directory.CreateDirectory($"{_appEnvironment.WebRootPath}/usersFiles/postsImages/{postId}");
            List<string> imagesPaths = new List<string>();
            Guid imageId = Guid.NewGuid();
            foreach (var image in images)
            {
                using (var fileStream = new FileStream($"{_appEnvironment.WebRootPath}/usersFiles/postsImages/{postId}/image{imageId}.png", FileMode.Create, FileAccess.Write))
                {
                    image.CopyTo(fileStream);
                    imagesPaths.Add($"/usersFiles/postsImages/{postId}/image{imageId}.png");
                }
                imageId = Guid.NewGuid();
            }

            return imagesPaths.ToArray();
        }
        
        private void DeleteAllImages(string[] pathsToImages)
        {
            string directoryName = Path.GetDirectoryName(_appEnvironment.WebRootPath + pathsToImages[0]);
            try

PePets/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PePets.Models;

namespace PePets.Controllers
{
    /// <summary>
    /// Контроллер для управления ролями пользователей.
    /// </summary>
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index() => View();

        /// <summary>
        /// Метод создает новую роль.
        /// </summary>
        /// <param name="name">Название новой роли.</param>
        /// <returns>
        /// При удачном создании роли редирект на страницу панели администрирования, при неудачном - представление 
        /// списка ролей с ошибками, возникшими при создании роли.
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        /// <summary>
        /// Метод удаляет определенную роль.
        /// </summary>
        /// <param name="id">Идентификатор роли, которую нужно удалить.</param>
        /// <returns>Редирект на страницу панели администрирования.</returns>
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Метод подгружает страницу для редактирования ролей определенного пользователя.
        /// </summary>
        /// <param name="id">Идентификатор пользователя, которому нужно редактировать роли.</param>
        /// <returns>
        /// Если пользователь существует, то возвращает представление редактирования ролей, если нет - страница с
        /// ошибкой, что нужная страница не найдена.
        /// </returns>
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    Name = user.FirstName,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }

        /// <summary>
        /// Метод редактирует роли для определенного пользователя.
        /// </summary>
        /// <param name="userId">Идентификатор пользователя, которому нужно редактировать роли.</param>
        /// <param name="roles">Список ролей, которое нужно выставить определенному пользователю.</param>
        /// <returns>
        /// Если роли отредактированы удачно, то редирект на панель администрирования, если неудачно - страница с
        /// ошибкой, что нужная страница не найдена.
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("Index");
            }

            return NotFound();
        }
    }
}

PePets/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/startPage.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/header.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/PostEdit.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/PostCard.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/UserProfile.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/PostReview.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Search.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/rating.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/ProfileEdit.css" asp-append-version="true" />
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<link rel="stylesheet" href="~/lib/bootstrapformhelpers/css/bootstrap-formhelpers.min.css" asp-append-version="true" />
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />

PePets/Views/Shared/FooterPartial.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - PePets - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

PePets/Views/Shared/HeaderPartial.cshtml
@inject PePets.Repositories.IUserRepository _userRepository

<header>
    <nav class="navbar navbar-expand-lg bg-info fixed-top">
        <div class="row justify-content-between align-items-center w-100">
            <div class="col-3 d-inline-flex">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img src="~/img/Logo.png" alt="Logo" width="50" height="50" />
                </a>
            </div>

            <div class="col-3 title text-center text-light">
                <h3>PePets</h3>
            </div>

            <div class="col-3 text-right user">
                @if (User.Identity.IsAuthenticated)
                {
                    <div>
                        <a class="dropdown-toggle text-decoration-none text-white" href="#" id="dropdownUserMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @await Component.InvokeAsync("AvatarPartial", User)
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownUserMenu">
                            <div class="list-group list-group-flush">
                                <a asp-controller="Users" asp-action="UserProfile" asp-route-id=@_userRepository.GetCurrentUser(User).Id class="dropdown-item list-group-item">Мой профиль</a>

                                <a href="#" class="dropdown-item list-group-item">
                                    Сообщения
                                    <span class="badge badge-primary badge-pill">5</span>
                                </a>

                                @if (User.IsInRole("admin"))
                                {
                                    <a class="dropdown-item list-group-item" asp-controller="Roles" asp-action="Index">Админка</a>
                                }
                                <form asp-controller="Account" asp-action="Logout" method="post">
                                    <button type="submit" class="dropdown-item list-group-item">Выйти</button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <button type="button" class="btn btn-outline-light" data-toggle="modal" data-target="#ModalAuth">
                        Войти
                    </button>
                }
            </div>
        </div>
        @await Component.InvokeAsync("IsEmailConfirmed", User.Identity.Name)
    </nav>
</header>

<div class="modal fade" id="ModalAuth" tabindex="-1" role="dialog" aria-labelledby="AuthLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            @await Html.PartialAsync("../Account/Login.cshtml", new PePets.Models.Login())

            @await Html.PartialAsync("../Account/Register.cshtml", new PePets.Models.Register())
        </div>
    </div>
</div>

PePets/Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}

@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

PePets/Views/Shared/ScriptsPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/bootstrapformhelpers/js/bootstrap-formhelpers.min.js" asp-append-version="true"></script>
<script src="https://kit.fontawesome.com/5da847b33b.js" crossorigin="anonymous"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<!--
<script src="~/js/scripts.min.js" asp-append-version="true"></script>
-->

PePets/Views/Shared/StartPagePartial.cshtml
<div class="startBlock">
    <div class="row align-items-center justify-content-around h-100">
        <div class="col-md-4 col-sm-12 text-center">
            <a href="javascript://0" onclick="SlowScroll('#postsPage')" class="btn btn-info btn-search">Найти объявление</a>
        </div>
        <div class="col-md-4 col-sm-12 text-center">
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Posts" asp-action="CreatePost" class="btn btn-primary btn-add" id="btn_search">Создать объявление</a>
            }
            else
            {
                <button data-toggle="modal" data-target="#ModalAuth" class="btn btn-primary btn-add">
                    Создать объявление
                </button>
            }
        </div>
    </div>
</div>

PePets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - PePets</title>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    @await Html.PartialAsync("HeaderPartial")

    @RenderBody()

    @await Html.PartialAsync("FooterPartial")

    @await Html.PartialAsync("ScriptsPartial")
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @RenderSection("Scripts", required: false)
</body>
</html>